camera_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: HttpResponseRedirect('/home')),
    path('home/', include('main.urls')),
]

main/urls.py
from django.urls import path, include
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('photo/', views.photo_view, name="photo_view"),
    path('takePhoto/', views.take_photo, name="take_photo")
    ]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from picamera import PiCamera
from time import sleep
from datetime import datetime

# Create your views here.


def index(request):
    return render(request, 'main/index.html')


def photo_view(request):
    return render(request, 'main/photo.html')


def take_photo(request):
	camera = PiCamera()
	camera.rotation = 180
	file_name = datetime.now().strftime('%Y_%m_%d_%Hh%Mm%Ss')
	camera.start_preview()
	sleep(3)
	camera.capture(f'./main/static/main/images/{file_name}.jpg')
	camera.stop_preview()
	camera.close()

	return HttpResponse(file_name)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Raspberry Camera {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

    {% load static %}
    <link href="{% static 'main/css/main.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'main/images/favicon.png' %}" type="image/png">
</head>
<body>
    <div id="nav_div" style="margin-bottom: 50px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Pi Camera</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:photo_view' %}">Take a photo</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </div>


    <div id="main_div" style="margin-left: 15px">
        {% block main %}
        {% endblock %}
    </div>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} Homepage {% endblock %}

{% block main %}
    <h2> Bienvenue sur le site de l'appareil photo Raspberry Pi (V2)</h2>
{% endblock %}

main/templates/main/photo.html
{% extends 'main/base.html' %}

{% block title %} Take a photo {% endblock %}

{% block main%}
    <div class="center">
            <h2 style="margin-bottom: 40px"> Appuie sur le bouton pour prendre une photo. <span style="font-size: 14px; font-style: italic">(Une fois prise, celle-ci sera affichée en dessous)</span></h2>
            <button type="button" class="btn" onclick="take_photo()">Prendre une photo</button>

    </div>
    <script>
    function take_photo() {
        $.get('{% url "main:take_photo" %}', (data) => {
            console.log("data is: ", data)
        })
    }
    </script>
{% endblock %}